// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EHRManagement.proto

package com.example.eHealthRecords.grpc;

public final class EHRManagementImpl {
  private EHRManagementImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EHRManagement_SearchPatientRecordRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EHRManagement_SearchPatientRecordRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EHRManagement_SearchPatientRecordResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EHRManagement_SearchPatientRecordResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EHRManagement_UpdatePatientRecordRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EHRManagement_UpdatePatientRecordRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EHRManagement_UpdatePatientRecordResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EHRManagement_UpdatePatientRecordResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EHRManagement_SharePatientRecordRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EHRManagement_SharePatientRecordRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EHRManagement_SharePatientRecordResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EHRManagement_SharePatientRecordResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023EHRManagement.proto\022\rEHRManagement\"0\n\032" +
      "SearchPatientRecordRequest\022\022\n\npatient_id" +
      "\030\001 \001(\t\"\237\001\n\033SearchPatientRecordResponse\022\022" +
      "\n\npatient_id\030\001 \001(\t\022\024\n\014patient_name\030\002 \001(\t" +
      "\022\022\n\ndepartment\030\003 \001(\t\022\021\n\tdiagnosis\030\004 \001(\t\022" +
      "\022\n\nmedication\030\005 \001(\t\022\033\n\023scheduled_operati" +
      "on\030\006 \001(\t\"M\n\032UpdatePatientRecordRequest\022\022" +
      "\n\npatient_id\030\001 \001(\t\022\033\n\023updated_informatio" +
      "n\030\002 \001(\t\"?\n\033UpdatePatientRecordResponse\022\017" +
      "\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"\\\n\031Shar" +
      "ePatientRecordRequest\022\022\n\npatient_id\030\001 \001(" +
      "\t\022\023\n\013record_part\030\002 \001(\t\022\026\n\016record_content" +
      "\030\003 \001(\t\">\n\032SharePatientRecordResponse\022\017\n\007" +
      "success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2\336\002\n\rEHRMa" +
      "nagement\022n\n\023SearchPatientRecord\022).EHRMan" +
      "agement.SearchPatientRecordRequest\032*.EHR" +
      "Management.SearchPatientRecordResponse\"\000" +
      "\022n\n\023UpdatePatientRecord\022).EHRManagement." +
      "UpdatePatientRecordRequest\032*.EHRManageme" +
      "nt.UpdatePatientRecordResponse\"\000\022m\n\022Shar" +
      "ePatientRecord\022(.EHRManagement.SharePati" +
      "entRecordRequest\032).EHRManagement.SharePa" +
      "tientRecordResponse\"\000(\001B6\n\037com.example.e" +
      "HealthRecords.grpcB\021EHRManagementImplP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EHRManagement_SearchPatientRecordRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EHRManagement_SearchPatientRecordRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EHRManagement_SearchPatientRecordRequest_descriptor,
        new java.lang.String[] { "PatientId", });
    internal_static_EHRManagement_SearchPatientRecordResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EHRManagement_SearchPatientRecordResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EHRManagement_SearchPatientRecordResponse_descriptor,
        new java.lang.String[] { "PatientId", "PatientName", "Department", "Diagnosis", "Medication", "ScheduledOperation", });
    internal_static_EHRManagement_UpdatePatientRecordRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_EHRManagement_UpdatePatientRecordRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EHRManagement_UpdatePatientRecordRequest_descriptor,
        new java.lang.String[] { "PatientId", "UpdatedInformation", });
    internal_static_EHRManagement_UpdatePatientRecordResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_EHRManagement_UpdatePatientRecordResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EHRManagement_UpdatePatientRecordResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_EHRManagement_SharePatientRecordRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_EHRManagement_SharePatientRecordRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EHRManagement_SharePatientRecordRequest_descriptor,
        new java.lang.String[] { "PatientId", "RecordPart", "RecordContent", });
    internal_static_EHRManagement_SharePatientRecordResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_EHRManagement_SharePatientRecordResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EHRManagement_SharePatientRecordResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
