// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EHRManagement.proto

package com.example.eHealthRecords.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EHRManagement.Empty)
    com.google.protobuf.MessageOrBuilder {
}
