// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EHRManagement.proto

package com.example.eHealthRecords.grpc;

public interface PatientIdsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EHRManagement.PatientIds)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string patient_ids = 1;</code>
   */
  java.util.List<java.lang.String>
      getPatientIdsList();
  /**
   * <code>repeated string patient_ids = 1;</code>
   */
  int getPatientIdsCount();
  /**
   * <code>repeated string patient_ids = 1;</code>
   */
  java.lang.String getPatientIds(int index);
  /**
   * <code>repeated string patient_ids = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientIdsBytes(int index);
}
