// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EHRManagement.proto

package com.example.eHealthRecords.grpc;

public interface PatientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EHRManagement.Patient)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string department = 3;</code>
   */
  java.lang.String getDepartment();
  /**
   * <code>string department = 3;</code>
   */
  com.google.protobuf.ByteString
      getDepartmentBytes();

  /**
   * <code>string diagnosis = 4;</code>
   */
  java.lang.String getDiagnosis();
  /**
   * <code>string diagnosis = 4;</code>
   */
  com.google.protobuf.ByteString
      getDiagnosisBytes();

  /**
   * <code>string medication = 5;</code>
   */
  java.lang.String getMedication();
  /**
   * <code>string medication = 5;</code>
   */
  com.google.protobuf.ByteString
      getMedicationBytes();

  /**
   * <code>string operation = 6;</code>
   */
  java.lang.String getOperation();
  /**
   * <code>string operation = 6;</code>
   */
  com.google.protobuf.ByteString
      getOperationBytes();
}
