// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EHRManagement.proto

package com.example.eHealthRecords.grpc;

public interface SharePatientRecordRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EHRManagement.SharePatientRecordRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patient_id = 1;</code>
   */
  java.lang.String getPatientId();
  /**
   * <code>string patient_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientIdBytes();

  /**
   * <code>string record_content = 2;</code>
   */
  java.lang.String getRecordContent();
  /**
   * <code>string record_content = 2;</code>
   */
  com.google.protobuf.ByteString
      getRecordContentBytes();
}
