// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EHRManagement.proto

package com.example.eHealthRecords.grpc;

public interface UpdatePatientRecordResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EHRManagement.UpdatePatientRecordResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.EHRManagement.Patient updated_patient = 3;</code>
   */
  boolean hasUpdatedPatient();
  /**
   * <code>.EHRManagement.Patient updated_patient = 3;</code>
   */
  com.example.eHealthRecords.grpc.Patient getUpdatedPatient();
  /**
   * <code>.EHRManagement.Patient updated_patient = 3;</code>
   */
  com.example.eHealthRecords.grpc.PatientOrBuilder getUpdatedPatientOrBuilder();
}
