// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EHRManagement.proto

package com.example.eHealthRecords.grpc;

public interface UpdatePatientRecordRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EHRManagement.UpdatePatientRecordRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patient_id = 1;</code>
   */
  java.lang.String getPatientId();
  /**
   * <code>string patient_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientIdBytes();

  /**
   * <code>string updated_information = 2;</code>
   */
  java.lang.String getUpdatedInformation();
  /**
   * <code>string updated_information = 2;</code>
   */
  com.google.protobuf.ByteString
      getUpdatedInformationBytes();
}
