// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientMedicationManagement.proto

package com.example.MedicationManagement.grpc;

/**
 * <pre>
 * Request message for AddMedication method
 * </pre>
 *
 * Protobuf type {@code PatientMedicationManagement.AddMedicationRequest}
 */
public  final class AddMedicationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PatientMedicationManagement.AddMedicationRequest)
    AddMedicationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddMedicationRequest.newBuilder() to construct.
  private AddMedicationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddMedicationRequest() {
    patientId_ = "";
    medicationName_ = "";
    dosage_ = "";
    sideEffects_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddMedicationRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            patientId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            medicationName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            dosage_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            sideEffects_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_AddMedicationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_AddMedicationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.MedicationManagement.grpc.AddMedicationRequest.class, com.example.MedicationManagement.grpc.AddMedicationRequest.Builder.class);
  }

  public static final int PATIENT_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object patientId_;
  /**
   * <code>string patient_id = 1;</code>
   */
  public java.lang.String getPatientId() {
    java.lang.Object ref = patientId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      patientId_ = s;
      return s;
    }
  }
  /**
   * <code>string patient_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPatientIdBytes() {
    java.lang.Object ref = patientId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      patientId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEDICATION_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object medicationName_;
  /**
   * <code>string medication_name = 2;</code>
   */
  public java.lang.String getMedicationName() {
    java.lang.Object ref = medicationName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      medicationName_ = s;
      return s;
    }
  }
  /**
   * <code>string medication_name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMedicationNameBytes() {
    java.lang.Object ref = medicationName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      medicationName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOSAGE_FIELD_NUMBER = 3;
  private volatile java.lang.Object dosage_;
  /**
   * <code>string dosage = 3;</code>
   */
  public java.lang.String getDosage() {
    java.lang.Object ref = dosage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dosage_ = s;
      return s;
    }
  }
  /**
   * <code>string dosage = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDosageBytes() {
    java.lang.Object ref = dosage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dosage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIDE_EFFECTS_FIELD_NUMBER = 4;
  private volatile java.lang.Object sideEffects_;
  /**
   * <code>string side_effects = 4;</code>
   */
  public java.lang.String getSideEffects() {
    java.lang.Object ref = sideEffects_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sideEffects_ = s;
      return s;
    }
  }
  /**
   * <code>string side_effects = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSideEffectsBytes() {
    java.lang.Object ref = sideEffects_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sideEffects_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPatientIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, patientId_);
    }
    if (!getMedicationNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, medicationName_);
    }
    if (!getDosageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dosage_);
    }
    if (!getSideEffectsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sideEffects_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPatientIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, patientId_);
    }
    if (!getMedicationNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, medicationName_);
    }
    if (!getDosageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dosage_);
    }
    if (!getSideEffectsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sideEffects_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.MedicationManagement.grpc.AddMedicationRequest)) {
      return super.equals(obj);
    }
    com.example.MedicationManagement.grpc.AddMedicationRequest other = (com.example.MedicationManagement.grpc.AddMedicationRequest) obj;

    boolean result = true;
    result = result && getPatientId()
        .equals(other.getPatientId());
    result = result && getMedicationName()
        .equals(other.getMedicationName());
    result = result && getDosage()
        .equals(other.getDosage());
    result = result && getSideEffects()
        .equals(other.getSideEffects());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PATIENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPatientId().hashCode();
    hash = (37 * hash) + MEDICATION_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getMedicationName().hashCode();
    hash = (37 * hash) + DOSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getDosage().hashCode();
    hash = (37 * hash) + SIDE_EFFECTS_FIELD_NUMBER;
    hash = (53 * hash) + getSideEffects().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.MedicationManagement.grpc.AddMedicationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.MedicationManagement.grpc.AddMedicationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.AddMedicationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.MedicationManagement.grpc.AddMedicationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.AddMedicationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.MedicationManagement.grpc.AddMedicationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.AddMedicationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.MedicationManagement.grpc.AddMedicationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.AddMedicationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.MedicationManagement.grpc.AddMedicationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.AddMedicationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.MedicationManagement.grpc.AddMedicationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.MedicationManagement.grpc.AddMedicationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request message for AddMedication method
   * </pre>
   *
   * Protobuf type {@code PatientMedicationManagement.AddMedicationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PatientMedicationManagement.AddMedicationRequest)
      com.example.MedicationManagement.grpc.AddMedicationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_AddMedicationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_AddMedicationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.MedicationManagement.grpc.AddMedicationRequest.class, com.example.MedicationManagement.grpc.AddMedicationRequest.Builder.class);
    }

    // Construct using com.example.MedicationManagement.grpc.AddMedicationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      patientId_ = "";

      medicationName_ = "";

      dosage_ = "";

      sideEffects_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_AddMedicationRequest_descriptor;
    }

    @java.lang.Override
    public com.example.MedicationManagement.grpc.AddMedicationRequest getDefaultInstanceForType() {
      return com.example.MedicationManagement.grpc.AddMedicationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.MedicationManagement.grpc.AddMedicationRequest build() {
      com.example.MedicationManagement.grpc.AddMedicationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.MedicationManagement.grpc.AddMedicationRequest buildPartial() {
      com.example.MedicationManagement.grpc.AddMedicationRequest result = new com.example.MedicationManagement.grpc.AddMedicationRequest(this);
      result.patientId_ = patientId_;
      result.medicationName_ = medicationName_;
      result.dosage_ = dosage_;
      result.sideEffects_ = sideEffects_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.MedicationManagement.grpc.AddMedicationRequest) {
        return mergeFrom((com.example.MedicationManagement.grpc.AddMedicationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.MedicationManagement.grpc.AddMedicationRequest other) {
      if (other == com.example.MedicationManagement.grpc.AddMedicationRequest.getDefaultInstance()) return this;
      if (!other.getPatientId().isEmpty()) {
        patientId_ = other.patientId_;
        onChanged();
      }
      if (!other.getMedicationName().isEmpty()) {
        medicationName_ = other.medicationName_;
        onChanged();
      }
      if (!other.getDosage().isEmpty()) {
        dosage_ = other.dosage_;
        onChanged();
      }
      if (!other.getSideEffects().isEmpty()) {
        sideEffects_ = other.sideEffects_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.MedicationManagement.grpc.AddMedicationRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.MedicationManagement.grpc.AddMedicationRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object patientId_ = "";
    /**
     * <code>string patient_id = 1;</code>
     */
    public java.lang.String getPatientId() {
      java.lang.Object ref = patientId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patientId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string patient_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPatientIdBytes() {
      java.lang.Object ref = patientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string patient_id = 1;</code>
     */
    public Builder setPatientId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      patientId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string patient_id = 1;</code>
     */
    public Builder clearPatientId() {
      
      patientId_ = getDefaultInstance().getPatientId();
      onChanged();
      return this;
    }
    /**
     * <code>string patient_id = 1;</code>
     */
    public Builder setPatientIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      patientId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object medicationName_ = "";
    /**
     * <code>string medication_name = 2;</code>
     */
    public java.lang.String getMedicationName() {
      java.lang.Object ref = medicationName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        medicationName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string medication_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMedicationNameBytes() {
      java.lang.Object ref = medicationName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        medicationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string medication_name = 2;</code>
     */
    public Builder setMedicationName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      medicationName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string medication_name = 2;</code>
     */
    public Builder clearMedicationName() {
      
      medicationName_ = getDefaultInstance().getMedicationName();
      onChanged();
      return this;
    }
    /**
     * <code>string medication_name = 2;</code>
     */
    public Builder setMedicationNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      medicationName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dosage_ = "";
    /**
     * <code>string dosage = 3;</code>
     */
    public java.lang.String getDosage() {
      java.lang.Object ref = dosage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dosage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dosage = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDosageBytes() {
      java.lang.Object ref = dosage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dosage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dosage = 3;</code>
     */
    public Builder setDosage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dosage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dosage = 3;</code>
     */
    public Builder clearDosage() {
      
      dosage_ = getDefaultInstance().getDosage();
      onChanged();
      return this;
    }
    /**
     * <code>string dosage = 3;</code>
     */
    public Builder setDosageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dosage_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sideEffects_ = "";
    /**
     * <code>string side_effects = 4;</code>
     */
    public java.lang.String getSideEffects() {
      java.lang.Object ref = sideEffects_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sideEffects_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string side_effects = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSideEffectsBytes() {
      java.lang.Object ref = sideEffects_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sideEffects_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string side_effects = 4;</code>
     */
    public Builder setSideEffects(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sideEffects_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string side_effects = 4;</code>
     */
    public Builder clearSideEffects() {
      
      sideEffects_ = getDefaultInstance().getSideEffects();
      onChanged();
      return this;
    }
    /**
     * <code>string side_effects = 4;</code>
     */
    public Builder setSideEffectsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sideEffects_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PatientMedicationManagement.AddMedicationRequest)
  }

  // @@protoc_insertion_point(class_scope:PatientMedicationManagement.AddMedicationRequest)
  private static final com.example.MedicationManagement.grpc.AddMedicationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.MedicationManagement.grpc.AddMedicationRequest();
  }

  public static com.example.MedicationManagement.grpc.AddMedicationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddMedicationRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddMedicationRequest>() {
    @java.lang.Override
    public AddMedicationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddMedicationRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddMedicationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddMedicationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.MedicationManagement.grpc.AddMedicationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

