// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientMedicationManagement.proto

package com.example.MedicationManagement.grpc;

public interface AdjustDosageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatientMedicationManagement.AdjustDosageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float adjustedInsulin = 1;</code>
   */
  float getAdjustedInsulin();

  /**
   * <code>float adjustedBloodSugar = 2;</code>
   */
  float getAdjustedBloodSugar();
}
