// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientMedicationManagement.proto

package com.example.MedicationManagement.grpc;

/**
 * <pre>
 * Streamed response message for AdjustDosage method
 * </pre>
 *
 * Protobuf type {@code PatientMedicationManagement.AdjustDosageResponse}
 */
public  final class AdjustDosageResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PatientMedicationManagement.AdjustDosageResponse)
    AdjustDosageResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AdjustDosageResponse.newBuilder() to construct.
  private AdjustDosageResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdjustDosageResponse() {
    adjustedInsulin_ = 0F;
    adjustedBloodSugar_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AdjustDosageResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            adjustedInsulin_ = input.readFloat();
            break;
          }
          case 21: {

            adjustedBloodSugar_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_AdjustDosageResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_AdjustDosageResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.MedicationManagement.grpc.AdjustDosageResponse.class, com.example.MedicationManagement.grpc.AdjustDosageResponse.Builder.class);
  }

  public static final int ADJUSTEDINSULIN_FIELD_NUMBER = 1;
  private float adjustedInsulin_;
  /**
   * <code>float adjustedInsulin = 1;</code>
   */
  public float getAdjustedInsulin() {
    return adjustedInsulin_;
  }

  public static final int ADJUSTEDBLOODSUGAR_FIELD_NUMBER = 2;
  private float adjustedBloodSugar_;
  /**
   * <code>float adjustedBloodSugar = 2;</code>
   */
  public float getAdjustedBloodSugar() {
    return adjustedBloodSugar_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (adjustedInsulin_ != 0F) {
      output.writeFloat(1, adjustedInsulin_);
    }
    if (adjustedBloodSugar_ != 0F) {
      output.writeFloat(2, adjustedBloodSugar_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (adjustedInsulin_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, adjustedInsulin_);
    }
    if (adjustedBloodSugar_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, adjustedBloodSugar_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.MedicationManagement.grpc.AdjustDosageResponse)) {
      return super.equals(obj);
    }
    com.example.MedicationManagement.grpc.AdjustDosageResponse other = (com.example.MedicationManagement.grpc.AdjustDosageResponse) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getAdjustedInsulin())
        == java.lang.Float.floatToIntBits(
            other.getAdjustedInsulin()));
    result = result && (
        java.lang.Float.floatToIntBits(getAdjustedBloodSugar())
        == java.lang.Float.floatToIntBits(
            other.getAdjustedBloodSugar()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ADJUSTEDINSULIN_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getAdjustedInsulin());
    hash = (37 * hash) + ADJUSTEDBLOODSUGAR_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getAdjustedBloodSugar());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.MedicationManagement.grpc.AdjustDosageResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.MedicationManagement.grpc.AdjustDosageResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.AdjustDosageResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.MedicationManagement.grpc.AdjustDosageResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.AdjustDosageResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.MedicationManagement.grpc.AdjustDosageResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.AdjustDosageResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.MedicationManagement.grpc.AdjustDosageResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.AdjustDosageResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.MedicationManagement.grpc.AdjustDosageResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.AdjustDosageResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.MedicationManagement.grpc.AdjustDosageResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.MedicationManagement.grpc.AdjustDosageResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Streamed response message for AdjustDosage method
   * </pre>
   *
   * Protobuf type {@code PatientMedicationManagement.AdjustDosageResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PatientMedicationManagement.AdjustDosageResponse)
      com.example.MedicationManagement.grpc.AdjustDosageResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_AdjustDosageResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_AdjustDosageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.MedicationManagement.grpc.AdjustDosageResponse.class, com.example.MedicationManagement.grpc.AdjustDosageResponse.Builder.class);
    }

    // Construct using com.example.MedicationManagement.grpc.AdjustDosageResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      adjustedInsulin_ = 0F;

      adjustedBloodSugar_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_AdjustDosageResponse_descriptor;
    }

    @java.lang.Override
    public com.example.MedicationManagement.grpc.AdjustDosageResponse getDefaultInstanceForType() {
      return com.example.MedicationManagement.grpc.AdjustDosageResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.MedicationManagement.grpc.AdjustDosageResponse build() {
      com.example.MedicationManagement.grpc.AdjustDosageResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.MedicationManagement.grpc.AdjustDosageResponse buildPartial() {
      com.example.MedicationManagement.grpc.AdjustDosageResponse result = new com.example.MedicationManagement.grpc.AdjustDosageResponse(this);
      result.adjustedInsulin_ = adjustedInsulin_;
      result.adjustedBloodSugar_ = adjustedBloodSugar_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.MedicationManagement.grpc.AdjustDosageResponse) {
        return mergeFrom((com.example.MedicationManagement.grpc.AdjustDosageResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.MedicationManagement.grpc.AdjustDosageResponse other) {
      if (other == com.example.MedicationManagement.grpc.AdjustDosageResponse.getDefaultInstance()) return this;
      if (other.getAdjustedInsulin() != 0F) {
        setAdjustedInsulin(other.getAdjustedInsulin());
      }
      if (other.getAdjustedBloodSugar() != 0F) {
        setAdjustedBloodSugar(other.getAdjustedBloodSugar());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.MedicationManagement.grpc.AdjustDosageResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.MedicationManagement.grpc.AdjustDosageResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float adjustedInsulin_ ;
    /**
     * <code>float adjustedInsulin = 1;</code>
     */
    public float getAdjustedInsulin() {
      return adjustedInsulin_;
    }
    /**
     * <code>float adjustedInsulin = 1;</code>
     */
    public Builder setAdjustedInsulin(float value) {
      
      adjustedInsulin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float adjustedInsulin = 1;</code>
     */
    public Builder clearAdjustedInsulin() {
      
      adjustedInsulin_ = 0F;
      onChanged();
      return this;
    }

    private float adjustedBloodSugar_ ;
    /**
     * <code>float adjustedBloodSugar = 2;</code>
     */
    public float getAdjustedBloodSugar() {
      return adjustedBloodSugar_;
    }
    /**
     * <code>float adjustedBloodSugar = 2;</code>
     */
    public Builder setAdjustedBloodSugar(float value) {
      
      adjustedBloodSugar_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float adjustedBloodSugar = 2;</code>
     */
    public Builder clearAdjustedBloodSugar() {
      
      adjustedBloodSugar_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PatientMedicationManagement.AdjustDosageResponse)
  }

  // @@protoc_insertion_point(class_scope:PatientMedicationManagement.AdjustDosageResponse)
  private static final com.example.MedicationManagement.grpc.AdjustDosageResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.MedicationManagement.grpc.AdjustDosageResponse();
  }

  public static com.example.MedicationManagement.grpc.AdjustDosageResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdjustDosageResponse>
      PARSER = new com.google.protobuf.AbstractParser<AdjustDosageResponse>() {
    @java.lang.Override
    public AdjustDosageResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AdjustDosageResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AdjustDosageResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdjustDosageResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.MedicationManagement.grpc.AdjustDosageResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

