// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientMedicationManagement.proto

package com.example.MedicationManagement.grpc;

public interface ConfirmMedicationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatientMedicationManagement.ConfirmMedicationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string contraindications = 2;</code>
   */
  java.lang.String getContraindications();
  /**
   * <code>string contraindications = 2;</code>
   */
  com.google.protobuf.ByteString
      getContraindicationsBytes();

  /**
   * <code>string administration_instructions = 3;</code>
   */
  java.lang.String getAdministrationInstructions();
  /**
   * <code>string administration_instructions = 3;</code>
   */
  com.google.protobuf.ByteString
      getAdministrationInstructionsBytes();
}
