// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientMedicationManagement.proto

package com.example.MedicationManagement.grpc;

public interface ConfirmMedicationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatientMedicationManagement.ConfirmMedicationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string medication_name = 1;</code>
   */
  java.lang.String getMedicationName();
  /**
   * <code>string medication_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getMedicationNameBytes();

  /**
   * <code>string dosage = 2;</code>
   */
  java.lang.String getDosage();
  /**
   * <code>string dosage = 2;</code>
   */
  com.google.protobuf.ByteString
      getDosageBytes();
}
