// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientMedicationManagement.proto

package com.example.MedicationManagement.grpc;

/**
 * <pre>
 * Response message for ConfirmMedication method
 * </pre>
 *
 * Protobuf type {@code PatientMedicationManagement.ConfirmMedicationResponse}
 */
public  final class ConfirmMedicationResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PatientMedicationManagement.ConfirmMedicationResponse)
    ConfirmMedicationResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConfirmMedicationResponse.newBuilder() to construct.
  private ConfirmMedicationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConfirmMedicationResponse() {
    message_ = "";
    contraindications_ = "";
    administrationInstructions_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ConfirmMedicationResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            contraindications_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            administrationInstructions_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_ConfirmMedicationResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_ConfirmMedicationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.MedicationManagement.grpc.ConfirmMedicationResponse.class, com.example.MedicationManagement.grpc.ConfirmMedicationResponse.Builder.class);
  }

  public static final int MESSAGE_FIELD_NUMBER = 1;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 1;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTRAINDICATIONS_FIELD_NUMBER = 2;
  private volatile java.lang.Object contraindications_;
  /**
   * <code>string contraindications = 2;</code>
   */
  public java.lang.String getContraindications() {
    java.lang.Object ref = contraindications_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contraindications_ = s;
      return s;
    }
  }
  /**
   * <code>string contraindications = 2;</code>
   */
  public com.google.protobuf.ByteString
      getContraindicationsBytes() {
    java.lang.Object ref = contraindications_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contraindications_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADMINISTRATION_INSTRUCTIONS_FIELD_NUMBER = 3;
  private volatile java.lang.Object administrationInstructions_;
  /**
   * <code>string administration_instructions = 3;</code>
   */
  public java.lang.String getAdministrationInstructions() {
    java.lang.Object ref = administrationInstructions_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      administrationInstructions_ = s;
      return s;
    }
  }
  /**
   * <code>string administration_instructions = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAdministrationInstructionsBytes() {
    java.lang.Object ref = administrationInstructions_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      administrationInstructions_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
    }
    if (!getContraindicationsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, contraindications_);
    }
    if (!getAdministrationInstructionsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, administrationInstructions_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
    }
    if (!getContraindicationsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, contraindications_);
    }
    if (!getAdministrationInstructionsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, administrationInstructions_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.MedicationManagement.grpc.ConfirmMedicationResponse)) {
      return super.equals(obj);
    }
    com.example.MedicationManagement.grpc.ConfirmMedicationResponse other = (com.example.MedicationManagement.grpc.ConfirmMedicationResponse) obj;

    boolean result = true;
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && getContraindications()
        .equals(other.getContraindications());
    result = result && getAdministrationInstructions()
        .equals(other.getAdministrationInstructions());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + CONTRAINDICATIONS_FIELD_NUMBER;
    hash = (53 * hash) + getContraindications().hashCode();
    hash = (37 * hash) + ADMINISTRATION_INSTRUCTIONS_FIELD_NUMBER;
    hash = (53 * hash) + getAdministrationInstructions().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.MedicationManagement.grpc.ConfirmMedicationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.MedicationManagement.grpc.ConfirmMedicationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.ConfirmMedicationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.MedicationManagement.grpc.ConfirmMedicationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.ConfirmMedicationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.MedicationManagement.grpc.ConfirmMedicationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.ConfirmMedicationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.MedicationManagement.grpc.ConfirmMedicationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.ConfirmMedicationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.MedicationManagement.grpc.ConfirmMedicationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.ConfirmMedicationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.MedicationManagement.grpc.ConfirmMedicationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.MedicationManagement.grpc.ConfirmMedicationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response message for ConfirmMedication method
   * </pre>
   *
   * Protobuf type {@code PatientMedicationManagement.ConfirmMedicationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PatientMedicationManagement.ConfirmMedicationResponse)
      com.example.MedicationManagement.grpc.ConfirmMedicationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_ConfirmMedicationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_ConfirmMedicationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.MedicationManagement.grpc.ConfirmMedicationResponse.class, com.example.MedicationManagement.grpc.ConfirmMedicationResponse.Builder.class);
    }

    // Construct using com.example.MedicationManagement.grpc.ConfirmMedicationResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      message_ = "";

      contraindications_ = "";

      administrationInstructions_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_ConfirmMedicationResponse_descriptor;
    }

    @java.lang.Override
    public com.example.MedicationManagement.grpc.ConfirmMedicationResponse getDefaultInstanceForType() {
      return com.example.MedicationManagement.grpc.ConfirmMedicationResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.MedicationManagement.grpc.ConfirmMedicationResponse build() {
      com.example.MedicationManagement.grpc.ConfirmMedicationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.MedicationManagement.grpc.ConfirmMedicationResponse buildPartial() {
      com.example.MedicationManagement.grpc.ConfirmMedicationResponse result = new com.example.MedicationManagement.grpc.ConfirmMedicationResponse(this);
      result.message_ = message_;
      result.contraindications_ = contraindications_;
      result.administrationInstructions_ = administrationInstructions_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.MedicationManagement.grpc.ConfirmMedicationResponse) {
        return mergeFrom((com.example.MedicationManagement.grpc.ConfirmMedicationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.MedicationManagement.grpc.ConfirmMedicationResponse other) {
      if (other == com.example.MedicationManagement.grpc.ConfirmMedicationResponse.getDefaultInstance()) return this;
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (!other.getContraindications().isEmpty()) {
        contraindications_ = other.contraindications_;
        onChanged();
      }
      if (!other.getAdministrationInstructions().isEmpty()) {
        administrationInstructions_ = other.administrationInstructions_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.MedicationManagement.grpc.ConfirmMedicationResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.MedicationManagement.grpc.ConfirmMedicationResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 1;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 1;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 1;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object contraindications_ = "";
    /**
     * <code>string contraindications = 2;</code>
     */
    public java.lang.String getContraindications() {
      java.lang.Object ref = contraindications_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contraindications_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contraindications = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContraindicationsBytes() {
      java.lang.Object ref = contraindications_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contraindications_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contraindications = 2;</code>
     */
    public Builder setContraindications(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contraindications_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contraindications = 2;</code>
     */
    public Builder clearContraindications() {
      
      contraindications_ = getDefaultInstance().getContraindications();
      onChanged();
      return this;
    }
    /**
     * <code>string contraindications = 2;</code>
     */
    public Builder setContraindicationsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contraindications_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object administrationInstructions_ = "";
    /**
     * <code>string administration_instructions = 3;</code>
     */
    public java.lang.String getAdministrationInstructions() {
      java.lang.Object ref = administrationInstructions_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        administrationInstructions_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string administration_instructions = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAdministrationInstructionsBytes() {
      java.lang.Object ref = administrationInstructions_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        administrationInstructions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string administration_instructions = 3;</code>
     */
    public Builder setAdministrationInstructions(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      administrationInstructions_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string administration_instructions = 3;</code>
     */
    public Builder clearAdministrationInstructions() {
      
      administrationInstructions_ = getDefaultInstance().getAdministrationInstructions();
      onChanged();
      return this;
    }
    /**
     * <code>string administration_instructions = 3;</code>
     */
    public Builder setAdministrationInstructionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      administrationInstructions_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PatientMedicationManagement.ConfirmMedicationResponse)
  }

  // @@protoc_insertion_point(class_scope:PatientMedicationManagement.ConfirmMedicationResponse)
  private static final com.example.MedicationManagement.grpc.ConfirmMedicationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.MedicationManagement.grpc.ConfirmMedicationResponse();
  }

  public static com.example.MedicationManagement.grpc.ConfirmMedicationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConfirmMedicationResponse>
      PARSER = new com.google.protobuf.AbstractParser<ConfirmMedicationResponse>() {
    @java.lang.Override
    public ConfirmMedicationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ConfirmMedicationResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ConfirmMedicationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConfirmMedicationResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.MedicationManagement.grpc.ConfirmMedicationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

