// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientMedicationManagement.proto

package com.example.MedicationManagement.grpc;

public interface GetMedicationScheduleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatientMedicationManagement.GetMedicationScheduleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patient_id = 1;</code>
   */
  java.lang.String getPatientId();
  /**
   * <code>string patient_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientIdBytes();

  /**
   * <code>int32 days = 2;</code>
   */
  int getDays();
}
