// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientMedicationManagement.proto

package com.example.MedicationManagement.grpc;

/**
 * <pre>
 * Streamed response message for GetMedicationSchedule method
 * </pre>
 *
 * Protobuf type {@code PatientMedicationManagement.GetMedicationScheduleResponse}
 */
public  final class GetMedicationScheduleResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PatientMedicationManagement.GetMedicationScheduleResponse)
    GetMedicationScheduleResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetMedicationScheduleResponse.newBuilder() to construct.
  private GetMedicationScheduleResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetMedicationScheduleResponse() {
    medicationName_ = "";
    scheduledTime_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetMedicationScheduleResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            medicationName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            scheduledTime_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_GetMedicationScheduleResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_GetMedicationScheduleResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.MedicationManagement.grpc.GetMedicationScheduleResponse.class, com.example.MedicationManagement.grpc.GetMedicationScheduleResponse.Builder.class);
  }

  public static final int MEDICATION_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object medicationName_;
  /**
   * <code>string medication_name = 1;</code>
   */
  public java.lang.String getMedicationName() {
    java.lang.Object ref = medicationName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      medicationName_ = s;
      return s;
    }
  }
  /**
   * <code>string medication_name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMedicationNameBytes() {
    java.lang.Object ref = medicationName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      medicationName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCHEDULED_TIME_FIELD_NUMBER = 2;
  private volatile java.lang.Object scheduledTime_;
  /**
   * <code>string scheduled_time = 2;</code>
   */
  public java.lang.String getScheduledTime() {
    java.lang.Object ref = scheduledTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scheduledTime_ = s;
      return s;
    }
  }
  /**
   * <code>string scheduled_time = 2;</code>
   */
  public com.google.protobuf.ByteString
      getScheduledTimeBytes() {
    java.lang.Object ref = scheduledTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scheduledTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMedicationNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, medicationName_);
    }
    if (!getScheduledTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, scheduledTime_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMedicationNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, medicationName_);
    }
    if (!getScheduledTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, scheduledTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.MedicationManagement.grpc.GetMedicationScheduleResponse)) {
      return super.equals(obj);
    }
    com.example.MedicationManagement.grpc.GetMedicationScheduleResponse other = (com.example.MedicationManagement.grpc.GetMedicationScheduleResponse) obj;

    boolean result = true;
    result = result && getMedicationName()
        .equals(other.getMedicationName());
    result = result && getScheduledTime()
        .equals(other.getScheduledTime());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MEDICATION_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getMedicationName().hashCode();
    hash = (37 * hash) + SCHEDULED_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getScheduledTime().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.MedicationManagement.grpc.GetMedicationScheduleResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.MedicationManagement.grpc.GetMedicationScheduleResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.GetMedicationScheduleResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.MedicationManagement.grpc.GetMedicationScheduleResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.GetMedicationScheduleResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.MedicationManagement.grpc.GetMedicationScheduleResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.GetMedicationScheduleResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.MedicationManagement.grpc.GetMedicationScheduleResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.GetMedicationScheduleResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.MedicationManagement.grpc.GetMedicationScheduleResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.MedicationManagement.grpc.GetMedicationScheduleResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.MedicationManagement.grpc.GetMedicationScheduleResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.MedicationManagement.grpc.GetMedicationScheduleResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Streamed response message for GetMedicationSchedule method
   * </pre>
   *
   * Protobuf type {@code PatientMedicationManagement.GetMedicationScheduleResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PatientMedicationManagement.GetMedicationScheduleResponse)
      com.example.MedicationManagement.grpc.GetMedicationScheduleResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_GetMedicationScheduleResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_GetMedicationScheduleResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.MedicationManagement.grpc.GetMedicationScheduleResponse.class, com.example.MedicationManagement.grpc.GetMedicationScheduleResponse.Builder.class);
    }

    // Construct using com.example.MedicationManagement.grpc.GetMedicationScheduleResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      medicationName_ = "";

      scheduledTime_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.MedicationManagement.grpc.PatientMedicationImpl.internal_static_PatientMedicationManagement_GetMedicationScheduleResponse_descriptor;
    }

    @java.lang.Override
    public com.example.MedicationManagement.grpc.GetMedicationScheduleResponse getDefaultInstanceForType() {
      return com.example.MedicationManagement.grpc.GetMedicationScheduleResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.MedicationManagement.grpc.GetMedicationScheduleResponse build() {
      com.example.MedicationManagement.grpc.GetMedicationScheduleResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.MedicationManagement.grpc.GetMedicationScheduleResponse buildPartial() {
      com.example.MedicationManagement.grpc.GetMedicationScheduleResponse result = new com.example.MedicationManagement.grpc.GetMedicationScheduleResponse(this);
      result.medicationName_ = medicationName_;
      result.scheduledTime_ = scheduledTime_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.MedicationManagement.grpc.GetMedicationScheduleResponse) {
        return mergeFrom((com.example.MedicationManagement.grpc.GetMedicationScheduleResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.MedicationManagement.grpc.GetMedicationScheduleResponse other) {
      if (other == com.example.MedicationManagement.grpc.GetMedicationScheduleResponse.getDefaultInstance()) return this;
      if (!other.getMedicationName().isEmpty()) {
        medicationName_ = other.medicationName_;
        onChanged();
      }
      if (!other.getScheduledTime().isEmpty()) {
        scheduledTime_ = other.scheduledTime_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.MedicationManagement.grpc.GetMedicationScheduleResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.MedicationManagement.grpc.GetMedicationScheduleResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object medicationName_ = "";
    /**
     * <code>string medication_name = 1;</code>
     */
    public java.lang.String getMedicationName() {
      java.lang.Object ref = medicationName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        medicationName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string medication_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMedicationNameBytes() {
      java.lang.Object ref = medicationName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        medicationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string medication_name = 1;</code>
     */
    public Builder setMedicationName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      medicationName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string medication_name = 1;</code>
     */
    public Builder clearMedicationName() {
      
      medicationName_ = getDefaultInstance().getMedicationName();
      onChanged();
      return this;
    }
    /**
     * <code>string medication_name = 1;</code>
     */
    public Builder setMedicationNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      medicationName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object scheduledTime_ = "";
    /**
     * <code>string scheduled_time = 2;</code>
     */
    public java.lang.String getScheduledTime() {
      java.lang.Object ref = scheduledTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scheduledTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string scheduled_time = 2;</code>
     */
    public com.google.protobuf.ByteString
        getScheduledTimeBytes() {
      java.lang.Object ref = scheduledTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scheduledTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string scheduled_time = 2;</code>
     */
    public Builder setScheduledTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      scheduledTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string scheduled_time = 2;</code>
     */
    public Builder clearScheduledTime() {
      
      scheduledTime_ = getDefaultInstance().getScheduledTime();
      onChanged();
      return this;
    }
    /**
     * <code>string scheduled_time = 2;</code>
     */
    public Builder setScheduledTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      scheduledTime_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PatientMedicationManagement.GetMedicationScheduleResponse)
  }

  // @@protoc_insertion_point(class_scope:PatientMedicationManagement.GetMedicationScheduleResponse)
  private static final com.example.MedicationManagement.grpc.GetMedicationScheduleResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.MedicationManagement.grpc.GetMedicationScheduleResponse();
  }

  public static com.example.MedicationManagement.grpc.GetMedicationScheduleResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetMedicationScheduleResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetMedicationScheduleResponse>() {
    @java.lang.Override
    public GetMedicationScheduleResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetMedicationScheduleResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetMedicationScheduleResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetMedicationScheduleResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.MedicationManagement.grpc.GetMedicationScheduleResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

