// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientMedicationManagement.proto

package com.example.MedicationManagement.grpc;

public interface GetMedicationScheduleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatientMedicationManagement.GetMedicationScheduleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string medication_name = 1;</code>
   */
  java.lang.String getMedicationName();
  /**
   * <code>string medication_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getMedicationNameBytes();

  /**
   * <code>string scheduled_time = 2;</code>
   */
  java.lang.String getScheduledTime();
  /**
   * <code>string scheduled_time = 2;</code>
   */
  com.google.protobuf.ByteString
      getScheduledTimeBytes();
}
