// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientMedicationManagement.proto

package com.example.MedicationManagement.grpc;

public final class PatientMedicationImpl {
  private PatientMedicationImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientMedicationManagement_AddMedicationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientMedicationManagement_AddMedicationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientMedicationManagement_AddMedicationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientMedicationManagement_AddMedicationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientMedicationManagement_GetMedicationScheduleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientMedicationManagement_GetMedicationScheduleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientMedicationManagement_GetMedicationScheduleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientMedicationManagement_GetMedicationScheduleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientMedicationManagement_ConfirmMedicationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientMedicationManagement_ConfirmMedicationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientMedicationManagement_ConfirmMedicationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientMedicationManagement_ConfirmMedicationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!PatientMedicationManagement.proto\022\033Pat" +
      "ientMedicationManagement\"i\n\024AddMedicatio" +
      "nRequest\022\022\n\npatient_id\030\001 \001(\t\022\027\n\017medicati" +
      "on_name\030\002 \001(\t\022\016\n\006dosage\030\003 \001(\t\022\024\n\014side_ef" +
      "fects\030\004 \001(\t\"9\n\025AddMedicationResponse\022\017\n\007" +
      "success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"@\n\034GetMed" +
      "icationScheduleRequest\022\022\n\npatient_id\030\001 \001" +
      "(\t\022\014\n\004days\030\002 \001(\005\"P\n\035GetMedicationSchedul" +
      "eResponse\022\027\n\017medication_name\030\001 \001(\t\022\026\n\016sc" +
      "heduled_time\030\002 \001(\t\"C\n\030ConfirmMedicationR" +
      "equest\022\027\n\017medication_name\030\001 \001(\t\022\016\n\006dosag" +
      "e\030\002 \001(\t\"l\n\031ConfirmMedicationResponse\022\017\n\007" +
      "message\030\001 \001(\t\022\031\n\021contraindications\030\002 \001(\t" +
      "\022#\n\033administration_instructions\030\003 \001(\t2\260\003" +
      "\n\024MedicationManagement\022x\n\rAddMedication\022" +
      "1.PatientMedicationManagement.AddMedicat" +
      "ionRequest\0322.PatientMedicationManagement" +
      ".AddMedicationResponse\"\000\022\222\001\n\025GetMedicati" +
      "onSchedule\0229.PatientMedicationManagement" +
      ".GetMedicationScheduleRequest\032:.PatientM" +
      "edicationManagement.GetMedicationSchedul" +
      "eResponse\"\0000\001\022\210\001\n\021ConfirmMedication\0225.Pa" +
      "tientMedicationManagement.ConfirmMedicat" +
      "ionRequest\0326.PatientMedicationManagement" +
      ".ConfirmMedicationResponse\"\000(\0010\001B@\n%com." +
      "example.MedicationManagement.grpcB\025Patie" +
      "ntMedicationImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PatientMedicationManagement_AddMedicationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PatientMedicationManagement_AddMedicationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientMedicationManagement_AddMedicationRequest_descriptor,
        new java.lang.String[] { "PatientId", "MedicationName", "Dosage", "SideEffects", });
    internal_static_PatientMedicationManagement_AddMedicationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PatientMedicationManagement_AddMedicationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientMedicationManagement_AddMedicationResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_PatientMedicationManagement_GetMedicationScheduleRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PatientMedicationManagement_GetMedicationScheduleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientMedicationManagement_GetMedicationScheduleRequest_descriptor,
        new java.lang.String[] { "PatientId", "Days", });
    internal_static_PatientMedicationManagement_GetMedicationScheduleResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PatientMedicationManagement_GetMedicationScheduleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientMedicationManagement_GetMedicationScheduleResponse_descriptor,
        new java.lang.String[] { "MedicationName", "ScheduledTime", });
    internal_static_PatientMedicationManagement_ConfirmMedicationRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PatientMedicationManagement_ConfirmMedicationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientMedicationManagement_ConfirmMedicationRequest_descriptor,
        new java.lang.String[] { "MedicationName", "Dosage", });
    internal_static_PatientMedicationManagement_ConfirmMedicationResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_PatientMedicationManagement_ConfirmMedicationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientMedicationManagement_ConfirmMedicationResponse_descriptor,
        new java.lang.String[] { "Message", "Contraindications", "AdministrationInstructions", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
