// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RealTimePatient.proto

package com.example.RealTimeMonitoring.grpc;

public interface AddPatientRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RealTimePatientMonitoring.AddPatientRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patient_name = 1;</code>
   */
  java.lang.String getPatientName();
  /**
   * <code>string patient_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientNameBytes();

  /**
   * <code>int32 patient_age = 2;</code>
   */
  int getPatientAge();

  /**
   * <code>string patient_id = 3;</code>
   */
  java.lang.String getPatientId();
  /**
   * <code>string patient_id = 3;</code>
   */
  com.google.protobuf.ByteString
      getPatientIdBytes();
}
