// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RealTimePatient.proto

package com.example.RealTimeMonitoring.grpc;

public interface AddPatientResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RealTimePatientMonitoring.AddPatientResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * response message for AddPatient method
   * </pre>
   *
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
