// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RealTimePatient.proto

package com.example.RealTimeMonitoring.grpc;

public final class RealTimePatientImpl {
  private RealTimePatientImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RealTimePatientMonitoring_AddPatientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RealTimePatientMonitoring_AddPatientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RealTimePatientMonitoring_AddPatientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RealTimePatientMonitoring_AddPatientResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RealTimePatientMonitoring_StreamPatientInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RealTimePatientMonitoring_StreamPatientInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RealTimePatientMonitoring_StreamPatientInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RealTimePatientMonitoring_StreamPatientInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RealTimePatientMonitoring_StreamMedicalAlertsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RealTimePatientMonitoring_StreamMedicalAlertsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RealTimePatientMonitoring_StreamMedicalAlertsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RealTimePatientMonitoring_StreamMedicalAlertsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025RealTimePatient.proto\022\031RealTimePatient" +
      "Monitoring\"R\n\021AddPatientRequest\022\024\n\014patie" +
      "nt_name\030\001 \001(\t\022\023\n\013patient_age\030\002 \001(\005\022\022\n\npa" +
      "tient_id\030\003 \001(\t\"6\n\022AddPatientResponse\022\017\n\007" +
      "success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"-\n\030Stream" +
      "PatientInfoRequest\022\021\n\tpatientId\030\001 \001(\t\"_\n" +
      "\031StreamPatientInfoResponse\022\021\n\theartRate\030" +
      "\001 \001(\001\022\030\n\020oxygenSaturation\030\002 \001(\001\022\025\n\rblood" +
      "Pressure\030\003 \001(\001\"/\n\032StreamMedicalAlertsReq" +
      "uest\022\021\n\tpatientId\030\001 \001(\t\"C\n\033StreamMedical" +
      "AlertsResponse\022\021\n\tdiagnosis\030\001 \001(\t\022\021\n\ttre" +
      "atment\030\002 \001(\t2\220\003\n\021PatientMonitoring\022k\n\nAd" +
      "dPatient\022,.RealTimePatientMonitoring.Add" +
      "PatientRequest\032-.RealTimePatientMonitori" +
      "ng.AddPatientResponse\"\000\022\202\001\n\021StreamPatien" +
      "tInfo\0223.RealTimePatientMonitoring.Stream" +
      "PatientInfoRequest\0324.RealTimePatientMoni" +
      "toring.StreamPatientInfoResponse\"\0000\001\022\210\001\n" +
      "\023StreamMedicalAlerts\0225.RealTimePatientMo" +
      "nitoring.StreamMedicalAlertsRequest\0326.Re" +
      "alTimePatientMonitoring.StreamMedicalAle" +
      "rtsResponse\"\0000\001B<\n#com.example.RealTimeM" +
      "onitoring.grpcB\023RealTimePatientImplP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RealTimePatientMonitoring_AddPatientRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RealTimePatientMonitoring_AddPatientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RealTimePatientMonitoring_AddPatientRequest_descriptor,
        new java.lang.String[] { "PatientName", "PatientAge", "PatientId", });
    internal_static_RealTimePatientMonitoring_AddPatientResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RealTimePatientMonitoring_AddPatientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RealTimePatientMonitoring_AddPatientResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_RealTimePatientMonitoring_StreamPatientInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RealTimePatientMonitoring_StreamPatientInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RealTimePatientMonitoring_StreamPatientInfoRequest_descriptor,
        new java.lang.String[] { "PatientId", });
    internal_static_RealTimePatientMonitoring_StreamPatientInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RealTimePatientMonitoring_StreamPatientInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RealTimePatientMonitoring_StreamPatientInfoResponse_descriptor,
        new java.lang.String[] { "HeartRate", "OxygenSaturation", "BloodPressure", });
    internal_static_RealTimePatientMonitoring_StreamMedicalAlertsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_RealTimePatientMonitoring_StreamMedicalAlertsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RealTimePatientMonitoring_StreamMedicalAlertsRequest_descriptor,
        new java.lang.String[] { "PatientId", });
    internal_static_RealTimePatientMonitoring_StreamMedicalAlertsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_RealTimePatientMonitoring_StreamMedicalAlertsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RealTimePatientMonitoring_StreamMedicalAlertsResponse_descriptor,
        new java.lang.String[] { "Diagnosis", "Treatment", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
