// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RealTimePatient.proto

package com.example.RealTimeMonitoring.grpc;

/**
 * Protobuf type {@code RealTimePatientMonitoring.StreamPatientInfoResponse}
 */
public  final class StreamPatientInfoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RealTimePatientMonitoring.StreamPatientInfoResponse)
    StreamPatientInfoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamPatientInfoResponse.newBuilder() to construct.
  private StreamPatientInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamPatientInfoResponse() {
    heartRate_ = 0D;
    oxygenSaturation_ = 0D;
    bloodPressure_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StreamPatientInfoResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            heartRate_ = input.readDouble();
            break;
          }
          case 17: {

            oxygenSaturation_ = input.readDouble();
            break;
          }
          case 25: {

            bloodPressure_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.RealTimeMonitoring.grpc.RealTimePatientImpl.internal_static_RealTimePatientMonitoring_StreamPatientInfoResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.RealTimeMonitoring.grpc.RealTimePatientImpl.internal_static_RealTimePatientMonitoring_StreamPatientInfoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse.class, com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse.Builder.class);
  }

  public static final int HEARTRATE_FIELD_NUMBER = 1;
  private double heartRate_;
  /**
   * <pre>
   * Streamed response message for StreamPatientInfo method
   * </pre>
   *
   * <code>double heartRate = 1;</code>
   */
  public double getHeartRate() {
    return heartRate_;
  }

  public static final int OXYGENSATURATION_FIELD_NUMBER = 2;
  private double oxygenSaturation_;
  /**
   * <code>double oxygenSaturation = 2;</code>
   */
  public double getOxygenSaturation() {
    return oxygenSaturation_;
  }

  public static final int BLOODPRESSURE_FIELD_NUMBER = 3;
  private double bloodPressure_;
  /**
   * <code>double bloodPressure = 3;</code>
   */
  public double getBloodPressure() {
    return bloodPressure_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (heartRate_ != 0D) {
      output.writeDouble(1, heartRate_);
    }
    if (oxygenSaturation_ != 0D) {
      output.writeDouble(2, oxygenSaturation_);
    }
    if (bloodPressure_ != 0D) {
      output.writeDouble(3, bloodPressure_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (heartRate_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, heartRate_);
    }
    if (oxygenSaturation_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, oxygenSaturation_);
    }
    if (bloodPressure_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, bloodPressure_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse)) {
      return super.equals(obj);
    }
    com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse other = (com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getHeartRate())
        == java.lang.Double.doubleToLongBits(
            other.getHeartRate()));
    result = result && (
        java.lang.Double.doubleToLongBits(getOxygenSaturation())
        == java.lang.Double.doubleToLongBits(
            other.getOxygenSaturation()));
    result = result && (
        java.lang.Double.doubleToLongBits(getBloodPressure())
        == java.lang.Double.doubleToLongBits(
            other.getBloodPressure()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HEARTRATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getHeartRate()));
    hash = (37 * hash) + OXYGENSATURATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getOxygenSaturation()));
    hash = (37 * hash) + BLOODPRESSURE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBloodPressure()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RealTimePatientMonitoring.StreamPatientInfoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RealTimePatientMonitoring.StreamPatientInfoResponse)
      com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.RealTimeMonitoring.grpc.RealTimePatientImpl.internal_static_RealTimePatientMonitoring_StreamPatientInfoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.RealTimeMonitoring.grpc.RealTimePatientImpl.internal_static_RealTimePatientMonitoring_StreamPatientInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse.class, com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse.Builder.class);
    }

    // Construct using com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      heartRate_ = 0D;

      oxygenSaturation_ = 0D;

      bloodPressure_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.RealTimeMonitoring.grpc.RealTimePatientImpl.internal_static_RealTimePatientMonitoring_StreamPatientInfoResponse_descriptor;
    }

    @java.lang.Override
    public com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse getDefaultInstanceForType() {
      return com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse build() {
      com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse buildPartial() {
      com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse result = new com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse(this);
      result.heartRate_ = heartRate_;
      result.oxygenSaturation_ = oxygenSaturation_;
      result.bloodPressure_ = bloodPressure_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse) {
        return mergeFrom((com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse other) {
      if (other == com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse.getDefaultInstance()) return this;
      if (other.getHeartRate() != 0D) {
        setHeartRate(other.getHeartRate());
      }
      if (other.getOxygenSaturation() != 0D) {
        setOxygenSaturation(other.getOxygenSaturation());
      }
      if (other.getBloodPressure() != 0D) {
        setBloodPressure(other.getBloodPressure());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double heartRate_ ;
    /**
     * <pre>
     * Streamed response message for StreamPatientInfo method
     * </pre>
     *
     * <code>double heartRate = 1;</code>
     */
    public double getHeartRate() {
      return heartRate_;
    }
    /**
     * <pre>
     * Streamed response message for StreamPatientInfo method
     * </pre>
     *
     * <code>double heartRate = 1;</code>
     */
    public Builder setHeartRate(double value) {
      
      heartRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Streamed response message for StreamPatientInfo method
     * </pre>
     *
     * <code>double heartRate = 1;</code>
     */
    public Builder clearHeartRate() {
      
      heartRate_ = 0D;
      onChanged();
      return this;
    }

    private double oxygenSaturation_ ;
    /**
     * <code>double oxygenSaturation = 2;</code>
     */
    public double getOxygenSaturation() {
      return oxygenSaturation_;
    }
    /**
     * <code>double oxygenSaturation = 2;</code>
     */
    public Builder setOxygenSaturation(double value) {
      
      oxygenSaturation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double oxygenSaturation = 2;</code>
     */
    public Builder clearOxygenSaturation() {
      
      oxygenSaturation_ = 0D;
      onChanged();
      return this;
    }

    private double bloodPressure_ ;
    /**
     * <code>double bloodPressure = 3;</code>
     */
    public double getBloodPressure() {
      return bloodPressure_;
    }
    /**
     * <code>double bloodPressure = 3;</code>
     */
    public Builder setBloodPressure(double value) {
      
      bloodPressure_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double bloodPressure = 3;</code>
     */
    public Builder clearBloodPressure() {
      
      bloodPressure_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RealTimePatientMonitoring.StreamPatientInfoResponse)
  }

  // @@protoc_insertion_point(class_scope:RealTimePatientMonitoring.StreamPatientInfoResponse)
  private static final com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse();
  }

  public static com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamPatientInfoResponse>
      PARSER = new com.google.protobuf.AbstractParser<StreamPatientInfoResponse>() {
    @java.lang.Override
    public StreamPatientInfoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StreamPatientInfoResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StreamPatientInfoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamPatientInfoResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.RealTimeMonitoring.grpc.StreamPatientInfoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

