// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RealTimePatient.proto

package com.example.RealTimeMonitoring.grpc;

public interface StreamPatientInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RealTimePatientMonitoring.StreamPatientInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * streamed response message for StreamPatientInfo method
   * </pre>
   *
   * <code>double heartRate = 1;</code>
   */
  double getHeartRate();

  /**
   * <code>double oxygenSaturation = 2;</code>
   */
  double getOxygenSaturation();

  /**
   * <code>double bloodPressure = 3;</code>
   */
  double getBloodPressure();
}
