// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RealTimePatient.proto

package com.example.RealTimeMonitoring.grpc;

/**
 * Protobuf type {@code RealTimePatientMonitoring.StreamMedicalAlertsResponse}
 */
public  final class StreamMedicalAlertsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RealTimePatientMonitoring.StreamMedicalAlertsResponse)
    StreamMedicalAlertsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamMedicalAlertsResponse.newBuilder() to construct.
  private StreamMedicalAlertsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamMedicalAlertsResponse() {
    diagnosis_ = "";
    treatment_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StreamMedicalAlertsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            diagnosis_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            treatment_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.RealTimeMonitoring.grpc.RealTimePatientImpl.internal_static_RealTimePatientMonitoring_StreamMedicalAlertsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.RealTimeMonitoring.grpc.RealTimePatientImpl.internal_static_RealTimePatientMonitoring_StreamMedicalAlertsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse.class, com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse.Builder.class);
  }

  public static final int DIAGNOSIS_FIELD_NUMBER = 1;
  private volatile java.lang.Object diagnosis_;
  /**
   * <pre>
   * Streamed response message for StreamMedicalAlerts method
   * </pre>
   *
   * <code>string diagnosis = 1;</code>
   */
  public java.lang.String getDiagnosis() {
    java.lang.Object ref = diagnosis_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      diagnosis_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Streamed response message for StreamMedicalAlerts method
   * </pre>
   *
   * <code>string diagnosis = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDiagnosisBytes() {
    java.lang.Object ref = diagnosis_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      diagnosis_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TREATMENT_FIELD_NUMBER = 2;
  private volatile java.lang.Object treatment_;
  /**
   * <code>string treatment = 2;</code>
   */
  public java.lang.String getTreatment() {
    java.lang.Object ref = treatment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      treatment_ = s;
      return s;
    }
  }
  /**
   * <code>string treatment = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTreatmentBytes() {
    java.lang.Object ref = treatment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      treatment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDiagnosisBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, diagnosis_);
    }
    if (!getTreatmentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, treatment_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDiagnosisBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, diagnosis_);
    }
    if (!getTreatmentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, treatment_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse)) {
      return super.equals(obj);
    }
    com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse other = (com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse) obj;

    boolean result = true;
    result = result && getDiagnosis()
        .equals(other.getDiagnosis());
    result = result && getTreatment()
        .equals(other.getTreatment());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DIAGNOSIS_FIELD_NUMBER;
    hash = (53 * hash) + getDiagnosis().hashCode();
    hash = (37 * hash) + TREATMENT_FIELD_NUMBER;
    hash = (53 * hash) + getTreatment().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RealTimePatientMonitoring.StreamMedicalAlertsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RealTimePatientMonitoring.StreamMedicalAlertsResponse)
      com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.RealTimeMonitoring.grpc.RealTimePatientImpl.internal_static_RealTimePatientMonitoring_StreamMedicalAlertsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.RealTimeMonitoring.grpc.RealTimePatientImpl.internal_static_RealTimePatientMonitoring_StreamMedicalAlertsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse.class, com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse.Builder.class);
    }

    // Construct using com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      diagnosis_ = "";

      treatment_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.RealTimeMonitoring.grpc.RealTimePatientImpl.internal_static_RealTimePatientMonitoring_StreamMedicalAlertsResponse_descriptor;
    }

    @java.lang.Override
    public com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse getDefaultInstanceForType() {
      return com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse build() {
      com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse buildPartial() {
      com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse result = new com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse(this);
      result.diagnosis_ = diagnosis_;
      result.treatment_ = treatment_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse) {
        return mergeFrom((com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse other) {
      if (other == com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse.getDefaultInstance()) return this;
      if (!other.getDiagnosis().isEmpty()) {
        diagnosis_ = other.diagnosis_;
        onChanged();
      }
      if (!other.getTreatment().isEmpty()) {
        treatment_ = other.treatment_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object diagnosis_ = "";
    /**
     * <pre>
     * Streamed response message for StreamMedicalAlerts method
     * </pre>
     *
     * <code>string diagnosis = 1;</code>
     */
    public java.lang.String getDiagnosis() {
      java.lang.Object ref = diagnosis_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        diagnosis_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Streamed response message for StreamMedicalAlerts method
     * </pre>
     *
     * <code>string diagnosis = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDiagnosisBytes() {
      java.lang.Object ref = diagnosis_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        diagnosis_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Streamed response message for StreamMedicalAlerts method
     * </pre>
     *
     * <code>string diagnosis = 1;</code>
     */
    public Builder setDiagnosis(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      diagnosis_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Streamed response message for StreamMedicalAlerts method
     * </pre>
     *
     * <code>string diagnosis = 1;</code>
     */
    public Builder clearDiagnosis() {
      
      diagnosis_ = getDefaultInstance().getDiagnosis();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Streamed response message for StreamMedicalAlerts method
     * </pre>
     *
     * <code>string diagnosis = 1;</code>
     */
    public Builder setDiagnosisBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      diagnosis_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object treatment_ = "";
    /**
     * <code>string treatment = 2;</code>
     */
    public java.lang.String getTreatment() {
      java.lang.Object ref = treatment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        treatment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string treatment = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTreatmentBytes() {
      java.lang.Object ref = treatment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        treatment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string treatment = 2;</code>
     */
    public Builder setTreatment(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      treatment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string treatment = 2;</code>
     */
    public Builder clearTreatment() {
      
      treatment_ = getDefaultInstance().getTreatment();
      onChanged();
      return this;
    }
    /**
     * <code>string treatment = 2;</code>
     */
    public Builder setTreatmentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      treatment_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RealTimePatientMonitoring.StreamMedicalAlertsResponse)
  }

  // @@protoc_insertion_point(class_scope:RealTimePatientMonitoring.StreamMedicalAlertsResponse)
  private static final com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse();
  }

  public static com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamMedicalAlertsResponse>
      PARSER = new com.google.protobuf.AbstractParser<StreamMedicalAlertsResponse>() {
    @java.lang.Override
    public StreamMedicalAlertsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StreamMedicalAlertsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StreamMedicalAlertsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamMedicalAlertsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.RealTimeMonitoring.grpc.StreamMedicalAlertsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

