// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RealTimePatient.proto

package com.example.RealTimeMonitoring.grpc;

public interface StreamMedicalAlertsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RealTimePatientMonitoring.StreamMedicalAlertsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Streamed response message for StreamMedicalAlerts method
   * </pre>
   *
   * <code>string diagnosis = 1;</code>
   */
  java.lang.String getDiagnosis();
  /**
   * <pre>
   * Streamed response message for StreamMedicalAlerts method
   * </pre>
   *
   * <code>string diagnosis = 1;</code>
   */
  com.google.protobuf.ByteString
      getDiagnosisBytes();

  /**
   * <code>string treatment = 2;</code>
   */
  java.lang.String getTreatment();
  /**
   * <code>string treatment = 2;</code>
   */
  com.google.protobuf.ByteString
      getTreatmentBytes();
}
