// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RealTimePatient.proto

package com.example.RealTimeMonitoring.grpc;

public interface StreamPatientInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RealTimePatientMonitoring.StreamPatientInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Request message for StreamPatientInfo method
   * </pre>
   *
   * <code>string patientId = 1;</code>
   */
  java.lang.String getPatientId();
  /**
   * <pre>
   * Request message for StreamPatientInfo method
   * </pre>
   *
   * <code>string patientId = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientIdBytes();
}
